### ISSUE TITLE
test failure for modesecurity 2.9.1 

### ISSUE THREAD

**Issue by azhao155** [SpiderLabs/OWASP-CRS-regressions#15]
Hi 
 I am using nginx 1.11.5 and modsecurity 2.9.1 for testing,  it's supposed to be 100% passing, but I did see some failure, here is one case:
Test case:930120-2
Test failed due to nothing printed in the error.log, I have configure the modesecurity as in the README, 
looked into detail, this rule is find any requests have the symbol defined in the lfi-os-files.data and block it , the request in the test has /etc/passwd, it should be a valid one but it seems to be modsecurity didn't do anything, do you see the same issue? We do want to use this regression test as the effectiveness testing tool and try to resolve all the failure, thanks in advance

**Comment by csanders-git** [comment]
we're still working on some kinks where for instance certain web servers don't allow for given responses. That being said, this repo isn't supported, instead please open a ticket on owasp-crs.
